image: tmaier/docker-compose:19.03
services:
  - docker:19.03-dind

before_script:
  - docker version
  - docker-compose version

after_script:
  - docker images

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  image: python:3.8
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run -av

.test-python-version: &test-python-version
  stage: test
  script:
    - docker-compose run tests

test-python-3.6:
  <<: *test-python-version
  variables:
    PY_VERSION: "3.6"

test-python-3.7:
  <<: *test-python-version
  variables:
    PY_VERSION: "3.7"

test-python-3.8:
  <<: *test-python-version
  variables:
    PY_VERSION: "3.8"

test-python-3.9:
  <<: *test-python-version
  variables:
    PY_VERSION: "3.9"

deploy:pypi:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install poetry
  script:
    - poetry publish -u $PYPI_U -p $PYPI_P --build
  only:
    - releases
