minimum_pre_commit_version: "2.3.0"
repos:
  - repo: "https://github.com/psf/black"
    rev: "21.4b2"
    hooks:
      - id: "black"
        name: "Format code (black)"
        language_version: "python3"
        exclude: ^docs/.*$

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "v1.10.0"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        language_version: "python3"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==20.8b1"

  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: "python3"
        additional_dependencies: [toml]

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v3.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"
      - id: "check-merge-conflict"

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        language_version: "python3"
        exclude: ^tests/.*$

  - repo: https://github.com/econchick/interrogate
    rev: 1.3.2  # or master if you're bold
    hooks:
      - id: interrogate
        language_version: "python3"
        args: [tests]

  - repo: "https://gitlab.com/PyCQA/flake8"
    rev: 3.9.1
    hooks:
      - id: "flake8"
        name: "Lint code (flake8)"
        language_version: "python3"
        additional_dependencies:
          - "flake8-broken-line==0.2.0"
          - "flake8-bugbear==20.1.4"
          - "flake8-builtins==1.5.2"
          - "flake8-comprehensions==3.2.2"
          - "flake8-eradicate==0.3.0"
          - "flake8-mutable==1.2.0"
          - "flake8-pie==0.5.0"
          - "flake8-quotes==3.0.0"
          - "flake8-string-format==0.3.0"
          - "flake8-tidy-imports==4.1.0"
          - "flake8-docstrings==1.5.0"
          - "pep8-naming==0.10.0"

  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.812"
    hooks:
      - id: "mypy"
        name: "Lint code (mypy)"
        language_version: "python3"
        exclude: ^tests/.*$
